# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
