# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180821_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissao',
            name='streamer_imagem',
            field=models.CharField(default='img/icons/user.png', max_length=255),
            preserve_default=False,
        ),
    ]
