# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_transmissao_streamer_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissao',
            name='views',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
