# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-17 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transmissao',
            old_name='hora',
            new_name='tempoLive',
        ),
    ]
