# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180917_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=4)),
                ('avaliado', models.CharField(max_length=1)),
                ('avaliador', models.CharField(max_length=1)),
            ],
        ),
    ]
