# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissao',
            name='avaliacao',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
